"""add shipment event table

Revision ID: 05907b0f73d6
Revises: 4b94f8668064
Create Date: 2026-04-29 22:59:43.505289

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "05907b0f73d6"
down_revision: Union[str, Sequence[str], None] = "4b94f8668064"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shipment_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("location", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(name="shipmentstatus", create_type=False),
            nullable=False,
        ),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "sellers",
        sa.Column("address", sa.String(), nullable=True),
    )
    op.add_column("sellers", sa.Column("zip_code", sa.Integer(), nullable=True))
    op.drop_column("shipments", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shipments",
        sa.Column(
            "status",
            postgresql.ENUM(
                "PLACED",
                "IN_TRANSIT",
                "DELIVERED",
                "OUT_FOR_DELIVERY",
                name="shipmentstatus",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("sellers", "zip_code")
    op.drop_column("sellers", "address")
    op.drop_table("shipment_event")
    # ### end Alembic commands ###
