"""change phone field str to int.

Revision ID: 0c758ffbd552
Revises: 3435c2f9639e
Create Date: 2026-05-05 21:44:05.426774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c758ffbd552'
down_revision: Union[str, Sequence[str], None] = '3435c2f9639e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("UPDATE delivery_partners SET email_verified = FALSE WHERE email_verified IS NULL")
    op.execute("UPDATE sellers SET email_verified = FALSE WHERE email_verified IS NULL")
    
    op.alter_column('delivery_partners', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sellers', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('shipments', 'client_contact_phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'client_contact_phone',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('sellers', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('delivery_partners', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
