"""add client_contact

Revision ID: 1c01286cbb52
Revises: 05907b0f73d6
Create Date: 2026-05-01 20:52:55.786253

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c01286cbb52'
down_revision: Union[str, Sequence[str], None] = '05907b0f73d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('client_contact_email', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('client_contact_phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'client_contact_phone')
    op.drop_column('shipments', 'client_contact_email')
    # ### end Alembic commands ###
