"""add email_verified field in User

Revision ID: 3435c2f9639e
Revises: 1c01286cbb52
Create Date: 2026-05-03 09:15:15.190636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3435c2f9639e'
down_revision: Union[str, Sequence[str], None] = '1c01286cbb52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partners', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('sellers', sa.Column('email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'email_verified')
    op.drop_column('delivery_partners', 'email_verified')
    # ### end Alembic commands ###
