"""add address column

Revision ID: 5bee7876dd98
Revises: e7eca3d3320a
Create Date: 2026-04-28 00:42:03.330928

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5bee7876dd98"
down_revision: Union[str, Sequence[str], None] = "e7eca3d3320a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shipments", sa.Column("address", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shipments", "address")
    # ### end Alembic commands ###
