"""add tag

Revision ID: 6ab3e4f5d0fc
Revises: 789272c11eb4
Create Date: 2026-05-09 13:14:02.328548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab3e4f5d0fc'
down_revision: Union[str, Sequence[str], None] = '789272c11eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'client_contact_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shipments', 'client_contact_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('tags', sa.Column('name', sa.Enum('EXPRESS', 'STANDARD', 'FRAGILE', 'HEAVY', 'INTERNATIONAL', 'DOMESTIC', 'TEMPERATYURE_CONTROLLED', 'GIFT', 'RETURN', 'DOCUMENTS', name='tagname'), nullable=False))
    op.add_column('tags', sa.Column('instruction', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'instruction')
    op.drop_column('tags', 'name')
    op.alter_column('shipments', 'client_contact_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shipments', 'client_contact_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
